Labs/A9. ASP.NET/A9. ASP.NET/Models/ErrorViewModel.cs
using System;

namespace A9._ASP.NET.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Models/SiteUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A9._ASP.NET.Models {
    public class SiteUser {
        public int id { get; set; }
        public String username { get; set; }
        public String password { get; set; }
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A9._ASP.NET.Models {
    public class User {
        // needed when I receive the new/updated user
        public User() { }
        public User(String name, String username, String password,
                    int age, String role, String profile, String email, String webpage) {
            this.name = name;
            this.username = username;
            this.password = password;
            this.age = age;
            this.role = role;
            this.profile = profile;
            this.email = email;
            this.webpage = webpage;
        }
        public int id { get; set; }
        public String name { get; set; }
        public String username { get; set; }
        public String password { get; set; }
        public int age { get; set; }
        public String role { get; set; }
        public String profile { get; set; }
        public String email { get; set; }
        public String webpage { get; set; }
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A9._ASP.NET.Data;
using A9._ASP.NET.Models;

namespace A9._ASP.NET.Controllers {
    [Route("[controller]")]
    public class AccountController : Controller {
        private readonly DBWpContext _context;
        public AccountController(DBWpContext context) {
            _context = context;
        }

        [HttpGet("login")]
        public IActionResult LoginGet() {
            if (HttpContext.Session.GetString("username") != null)
                return Redirect("~/users/dashboard");

            return View("Login");
        }

        [HttpPost("login")]
        public IActionResult LoginPost(String username, String password) {
            bool validCredentials = _context.Site_User.Any(user => user.username == username && user.password == password);

            if (validCredentials) {
                HttpContext.Session.SetString("username", username);
                return Redirect("~/users/dashboard");
            }
            else {
                return View("Login", "Username or password is invalid.");
            }
        }

        [HttpGet("logout")]
        public IActionResult Logout() {
            HttpContext.Session.Clear();
            return Redirect("~/account/login");
        }
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Controllers/HomeController.cs
using A9._ASP.NET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace A9._ASP.NET.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Controllers/UsersController.cs
using A9._ASP.NET.Data;
using A9._ASP.NET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A9._ASP.NET.Controllers {
    [Route("[controller]")]
    public class UsersController : Controller {
        private readonly DBWpContext _context;
        public UsersController(DBWpContext context) {
            _context = context;
        }

        [HttpGet("")]
        public IActionResult RedirectToDashBoard() {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            return Redirect("~/users/dashboard");
        }

        [HttpGet("dashboard")]
        public IActionResult Dashboard() {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            return View("Dashboard", _context.User.ToList());
        }

        [HttpGet("add")]
        public IActionResult AddGet() {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            return View("Add");
        }

        [HttpPost("add")]
        public IActionResult AddPost(User newUser) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            _context.Add(newUser);
            _context.SaveChanges();

            return Redirect("~/users/dashboard");
        }

        [HttpGet("get/role/")]
        public IActionResult GetByRole(String role) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            return View("Dashboard", _context.User.Where(user => user.role == role).ToList());
        }

        [HttpGet("get/name/")]
        public IActionResult GetByName(String name) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            return View("Dashboard", _context.User.Where(user => EF.Functions.Like(user.name, "%" + name + "%")).ToList());
        }

        [HttpGet("update/{id}")]
        public IActionResult UpdateGet(int id) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            var user = _context.User.First(user => user.id == id);
            return View("Update", user);
        }

        [HttpPost("update")]
        public IActionResult UpdatePost(User updatedUser) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            // obs: username field is unique
            User user = _context.User.FirstOrDefault(user => user.username == updatedUser.username);
            user.name = updatedUser.name;
            user.username = updatedUser.username;
            user.password = updatedUser.password;
            user.age = updatedUser.age;
            user.role = updatedUser.role;
            user.profile = updatedUser.profile;
            user.email = updatedUser.email;
            user.webpage = updatedUser.webpage;

            _context.SaveChanges();

            return Redirect("~/users/dashboard");
        }

        [HttpPost("delete/{id}")]
        public IActionResult Delete(int id) {
            if (HttpContext.Session.GetString("username") == null) {
                return Redirect("~/account/login");
            }

            User user = _context.User.FirstOrDefault(user => user.id == id);
            _context.User.Remove(user);
            _context.SaveChanges();

            return Redirect("~/users/dashboard");
        }
    }
}

Labs/A9. ASP.NET/A9. ASP.NET/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Labs/A9. ASP.NET/A9. ASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - A9._ASP.NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment 9</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - A9._ASP.NET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Labs/A9. ASP.NET/A9. ASP.NET/Views/Users/Add.cshtml
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('#create-form').validate({
                rules: {
                    name: {
                        required: true
                    },
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    },
                    age: {
                        required: true
                    },
                    role: {
                        required: true
                    },
                    profile: {
                        required: true
                    },
                    email: {
                        required: true
                    },
                    webpage: {
                        required: true
                    },
                },
                messages: {
                    name: {
                        required: "Please enter a name"
                    },
                    username: {
                        required: "Please enter a username"
                    },
                    password: {
                        required: "Please enter a password"
                    },
                    age: {
                        required: "Please enter an age"
                    },
                    role: {
                        required: "Please enter a role"
                    },
                    profile: {
                        required: "Please enter a profile"
                    },
                    email: {
                        required: "Please enter an email"
                    },
                    webpage: {
                        required: "Please enter a webpage"
                    },
                }
            });

        });
    </script>
}

<form id="create-form" asp-controller="Users" asp-action="AddPost" method="post">
    <label for="name">Name:</label>
    <input name="name" type="text" />
    <br>

    <label for="username">Userame:</label>
    <input name="username" type="text" />
    <br>

    <label for="password">Password:</label>
    <input name="password" type="text" />
    <br>

    <label for="age">Age:</label>
    <input name="age" type="text" />
    <br>

    <label for="role">Role:</label>
    <input name="role" type="text" />
    <br>

    <label for="profile">Profile:</label>
    <input name="profile" type="text" />
    <br>

    <label for="email">Email:</label>
    <input name="email" type="text" />
    <br>

    <label for="webpage">Webpage:</label>
    <input name="webpage" type="text" />
    <br>

    <input type="submit" value="Add" />
</form>

Labs/A9. ASP.NET/A9. ASP.NET/Views/Users/Dashboard.cshtml
<environment>
    <link rel="stylesheet" href="~/css/DashboardView.css" /> 
</environment>

@model List<User>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dashboard</title>
</head>
<body>
    <div id="container">
        <form asp-controller="Users" asp-action="AddGet" method="get">
            <input type="submit" value="Add new user">
        </form>

        <form asp-controller="Users" asp-action="GetByRole" method="get">
            <label for="role">Search by role:</label>
            <input name="role" type="text" />
            <input type="submit" value="Search" />
        </form>

        <form asp-controller="Users" asp-action="GetByName" method="get" style="display: block">
            <label for="name">Search by name:</label>
            <input name="name" type="text" />
            <input type="submit" value="Search" />
        </form>

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>Age</th>
                    <th>Role</th>
                    <th>Profile</th>
                    <th>Email</th>
                    <th>Webpage</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model) {
                    <tr>
                        <td>@user.name</td>
                        <td>@user.username</td>
                        <td>@user.password</td>
                        <td>@user.age</td>
                        <td>@user.role</td>
                        <td>@user.profile</td>
                        <td>@user.email</td>
                        <td>@user.webpage</td>
                        <td>
                            <form asp-controller="Users" asp-action="UpdateGet" method="get" asp-route-id="@user.id">
                                <input type="submit" value="Update">
                            </form>
                            <form asp-controller="Users" asp-action="Delete" method="post" asp-route-id="@user.id"
                                  onclick="return confirm('Are you sure you want to delete?')">
                                <input type="submit" value="Delete">
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <br />
</body>
</html>

Labs/A9. ASP.NET/A9. ASP.NET/Views/Users/Update.cshtml
@model User

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('#update-form').validate({
                rules: {
                    name: {
                        required: true
                    },
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    },
                    age: {
                        required: true
                    },
                    role: {
                        required: true
                    },
                    profile: {
                        required: true
                    },
                    email: {
                        required: true
                    },
                    webpage: {
                        required: true
                    },
                },
                messages: {
                    name: {
                        required: "Please enter a name"
                    },
                    username: {
                        required: "Please enter a username"
                    },
                    password: {
                        required: "Please enter a password"
                    },
                    age: {
                        required: "Please enter an age"
                    },
                    role: {
                        required: "Please enter a role"
                    },
                    profile: {
                        required: "Please enter a profile"
                    },
                    email: {
                        required: "Please enter an email"
                    },
                    webpage: {
                        required: "Please enter a webpage"
                    },
                }
            });

        });
    </script>
}

<form id="update-form" asp-controller="Users" asp-action="UpdatePost" method="post">
    <label for="name">Name:</label>
    <input name="name" type="text" value="@Model.name" />
    <br>

    <label for="username">Userame:</label>
    <input name="username" type="text" value="@Model.username" />
    <br>

    <label for="password">Password:</label>
    <input name="password" type="text" value="@Model.password" />
    <br>

    <label for="age">Age:</label>
    <input name="age" type="text" value="@Model.age" />
    <br>

    <label for="role">Role:</label>
    <input name="role" type="text" value="@Model.role" />
    <br>

    <label for="profile">Profile:</label>
    <input name="profile" type="text" value="@Model.profile" />
    <br>

    <label for="email">Email:</label>
    <input name="email" type="text" value="@Model.email" />
    <br>

    <label for="webpage">Webpage:</label>
    <input name="webpage" type="text" value="@Model.webpage" />
    <br>

    <input type="submit" value="Update" />
</form>